image: docker:git
services:
- docker:dind

stages:
- build

variables:
  CONTAINER_IMAGE: registry.gitlab.com/rechat/server:$CI_BUILD_REF_NAME

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.example.com

build:
  stage: build
  script:
    - docker build -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE