image: docker:git

stages:
  - build
  - test

variables:
  CONTAINER_IMAGE: registry.gitlab.com/rechat/server:$CI_BUILD_REF_NAME
  POSTGRES_DB: rechat
  POSTGRES_USER: rechat
  POSTGRES_PASSWORD: rechat

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build:
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE

test:
  stage: test
  services:
    - docker:dind
  script:
    - docker run -d -e POSTGRES_DB -e POSTGRES_USER -e POSTGRES_PASSWORD --name db -p 5432:5432 mdillon/postgis:9.6-alpine
    - docker run -d --name redis -p 6379:6379 redis:latest
    - docker ps
    - apk update
    - apk add postgresql-client
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - psql -q -h localhost -U $POSTGRES_USER $POSTGRES_DB < data/minimal.sql
    - export REDIS_URL="redis://db:6379"
    - export DATABASE_URL="postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db/$POSTGRES_DB"
    - ENVS=`env | sed -n '/^[^\t]/s/=.*//p' | sed '/^$/d' | sed 's/^/-e /g' | tr '\n' ' '`
    - docker run --link db:db --link redis:redis --link db:db $ENVS $CONTAINER_IMAGE npm run coverage