image: node:10-alpine

variables:
  ENV: development
  POSTGRES_DB: rechat
  POSTGRES_USER: rechat
  POSTGRES_PASSWORD: rechat
  DATABASE_URL: "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB"
  REDIS_URL: "redis://redis:6379"

modules:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  before_script:
    - apk --no-cache --update add git python build-base
  script:
    - NODE_ENV="$ENV" npm install
  tags:
    - docker

modules:docs:
  stage: build
  image: node:10-alpine
  cache:
    key: docs
    paths:
      - node_modules/
  before_script:
    - apk --no-cache --update add git python build-base
  script:
    - npm install async aglio commander
  tags:
    - docker

lint:
  stage: test
  dependencies:
    - modules
  script: npx eslint .
  tags:
    - docker

coverage:
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull
  dependencies:
    - modules
  services:
    - alias: postgres
      name: mdillon/postgis:10-alpine
    - alias: redis
      name: redis:latest
  before_script:
    - apk --no-cache --update add postgresql-client
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - psql -h "postgres" -U "$POSTGRES_USER" "$POSTGRES_DB" < ./data/minimal.sql
  script:
    - npm run coverage
  coverage: '/Lines\s+:\s([\d\.]+)/'
  artifacts:
    paths:
      - istanbul
      - docs
  tags:
    - docker

docs:
  stage: deploy
  image: node:10-alpine
  dependencies:
    - modules:docs
    - coverage
  cache:
    key: docs
    paths:
      - node_modules/
    policy: pull
  script:
    - node api_docs/index.js -o
  after_script:
    - apk --no-cache --update add ca-certificates wget
    - wget https://dl.minio.io/client/mc/release/linux-amd64/mc
    - chmod +x mc
    - ./mc config host add rechat https://minio.rechat.com "$MINIO_ACCESS_KEY" "$MINIO_SECRET_KEY"
    - ./mc cp --recursive docs/ rechat/docs/$CI_COMMIT_REF_NAME
  tags:
    - docker
