# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:
  - redis:latest
  - mdillon/postgis:9.6-alpine

tests:
  script:
   - apt-get update
   - apt-get install -y postgresql-client
   - export PGPASSWORD=$POSTGRES_PASSWORD
   - psql -q -h mdillon__postgis -U rechat rechat < data/minimal.sql
   - NODE_ENV=development npm install --no-progress
   - node_modules/istanbul/lib/cli.js cover --dir istanbul tests/run.js -- --report --stop-on-fail --concurrency 10
  artifacts:
   paths:
   - istanbul/lcov-report

variables:
  POSTGRES_DB: rechat
  POSTGRES_USER: rechat
  POSTGRES_PASSWORD: rechat