image: docker:git

stages:
  - build
  - test
  - docs

variables:
  CONTAINER_IMAGE: registry.gitlab.com/rechat/server:$CI_COMMIT_REF_NAME
  POSTGRES_DB: rechat
  POSTGRES_USER: rechat
  POSTGRES_PASSWORD: rechat

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE

test:
  stage: test
  script:
    - docker run -d -e POSTGRES_DB -e POSTGRES_USER -e POSTGRES_PASSWORD --name db mdillon/postgis:10-alpine
    - sleep 20
    - docker run -d --name redis redis:latest
    - docker cp ./data/minimal.sql db:/minimal.sql
    - docker exec db sh -c "psql -U $POSTGRES_USER $POSTGRES_DB < /minimal.sql"
    - export REDIS_URL="redis://redis:6379"
    - export DATABASE_URL="postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db/$POSTGRES_DB"
    - ENVS=`env | sed -n '/^[^\t]/s/=.*//p' | sed '/^$/d' | sed 's/^/-e /g' | tr '\n' ' '`
    - docker run --link db:db --link redis:redis --link db:db $ENVS $CONTAINER_IMAGE npm run coverage
    - docker run --name html --link db:db --link redis:redis --link db:db $ENVS $CONTAINER_IMAGE npm run docs
    - rm -rf /var/www/docs/rechat/$CI_COMMIT_REF_NAME
    - docker cp html:/tmp/rechat /var/www/docs/rechat/$CI_COMMIT_REF_NAME
  artifacts:
    paths:
      - istanbul

  before_script:
    - docker kill db redis html || true
    - docker rm   db redis html || true

  after_script:
    - docker kill db redis html || true
    - docker rm   db redis html || true
