image: docker:git

stages:
  - build
  - test

variables:
  CONTAINER_IMAGE: registry.gitlab.com/rechat/server:$CI_BUILD_REF_NAME
  POSTGRES_DB: rechat
  POSTGRES_USER: rechat
  POSTGRES_PASSWORD: rechat

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build:
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE

test:
  stage: test
  services:
    - redis:latest
    - mdillon/postgis:9.6-alpine
    - docker:dind
  script:
    - apk update
    - apk add postgresql-client
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - psql -q -h mdillon__postgis -U rechat rechat < data/minimal.sql
    - env
    - env > env.txt
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run --env-file env.txt $CONTAINER_TEST_IMAGE /app/node_modules/istanbul/lib/cli.js cover --dir istanbul tests/run.js -- --curl --stop-on-fail --concurrency 1