image: docker:git

stages:
  - build
  - test
  - docs

variables:
  CONTAINER_IMAGE: registry.gitlab.com/rechat/server:$CI_BUILD_REF_NAME
  DOCS_IMAGE: registry.gitlab.com/rechat/server:docs
  POSTGRES_DB: rechat
  POSTGRES_USER: rechat
  POSTGRES_PASSWORD: rechat

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE

test:
  stage: test
  services:
    - redis:latest
    - mdillon/postgis:9.6-alpine
  script:
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - psql -q -h mdillon__postgis -U rechat rechat < data/minimal.sql
    - docker run --link db:db --link redis:redis --link db:db $CONTAINER_IMAGE npm run coverage
    - docker run --name html --link db:db --link redis:redis --link db:db $CONTAINER_IMAGE npm run docs
    - docker cp html:/tmp/rechat /tmp/rechat
    - docker run -d --name docs nginx:alpine
    - docker cp /tmp/rechat docs:/usr/share/nginx/html
    - docker push $DOCS_IMAGE

variables:
  POSTGRES_DB: rechat
  POSTGRES_USER: rechat
  POSTGRES_PASSWORD: rechat

