apps:
  - script   : ./scripts/workers/index.js
    args     : ./peanar/common
    name     : 'peanar_common'
    kill_timeout : 25000
  - script   : ./scripts/workers/index.js
    args     : ./peanar/integrations
    name     : 'integrations'
    kill_timeout : 25000
  - script   : ./scripts/workers/index.js
    args     : ./peanar/email
    name     : 'email'
    kill_timeout : 25000
