apps:
  - script   : ./scripts/workers/index.js
    args     : ./kue/index
    name     : 'kue_workers'
    kill_timeout : 15000
  - script   : ./scripts/workers/index.js
    args     : ./peanar/microsoft_notifications
    name     : 'microsoft_notifications'
    kill_timeout : 15000
  - script   : ./scripts/workers/index.js
    args     : ./peanar/mls
    name     : 'mls'
    kill_timeout : 15000
  - script   : ./scripts/workers/index.js
    args     : ./peanar/mls_photos
    name     : 'mls_photos'
    kill_timeout : 15000
  - script   : ./scripts/workers/index.js
    args     : ./peanar/mls_photos_bulk
    name     : 'mls_photos_bulk'
    kill_timeout : 15000
  - script   : ./scripts/workers/index.js
    args     : ./peanar/email_campaign
    name     : 'email_campaign_worker'
    kill_timeout : 15000
