apps:
  - script   : ./scripts/workers/index.js
    args     : ./peanar/integrations
    name     : 'integrations'
    kill_timeout : 25000
  - script   : ./scripts/workers/index.js
    args     : ./peanar/email_misc
    name     : 'email'
    kill_timeout : 25000
  - script   : ./scripts/workers/index.js
    args     : ./peanar/email
    name     : 'email'
    kill_timeout : 25000
    instances: 1
